Better handle postinst

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,35 +1,76 @@
 #!/bin/sh
+# postinst script for tpr
+#
+# see: dh_installdeb(1)
 
 set -e
 
-# Make sure the tpr user exists
-if ! getent passwd tpr > /dev/null; then
-    adduser --system --quiet --home / --no-create-home \
-        --shell /bin/sh --group --gecos "The Pithy Reader" tpr
-fi
-# if the user was created manually, make sure the group is there as well
-if ! getent group tpr > /dev/null; then
-    addgroup --system --quiet tpr
-fi
-# make sure tpr is in the tpr group
-if ! id -Gn tpr | grep -qw tpr; then
-    adduser --quiet tpr tpr
-fi
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
-# check validity of tpr user and group
-if [ "`id -u tpr`" -eq 0 ]; then
-    echo "The tpr system user must not have uid 0 (root).
-Please fix this and reinstall this package." >&2
-    exit 1
-fi
-if [ "`id -g tpr`" -eq 0 ]; then
-    echo "The tpr system user must not have root as primary group.
-Please fix this and reinstall this package." >&2
-    exit 1
-fi
+ensure_users_and_permissions()
+{
+    # Make sure the tpr user exists
+    if ! getent passwd tpr > /dev/null; then
+        adduser --system --quiet --home / --no-create-home \
+            --shell /bin/sh --group --gecos "The Pithy Reader" tpr
+    fi
+    # if the user was created manually, make sure the group is there as well
+    if ! getent group tpr > /dev/null; then
+        addgroup --system --quiet tpr
+    fi
+    # make sure tpr is in the tpr group
+    if ! id -Gn tpr | grep -qw tpr; then
+        adduser --quiet tpr tpr
+    fi
 
-chown tpr:tpr /etc/tpr/tpr.conf
+    # check validity of tpr user and group
+    if [ "`id -u tpr`" -eq 0 ]; then
+        echo "The tpr system user must not have uid 0 (root).
+    Please fix this and reinstall this package." >&2
+        exit 1
+    fi
+    if [ "`id -g tpr`" -eq 0 ]; then
+        echo "The tpr system user must not have root as primary group.
+    Please fix this and reinstall this package." >&2
+        exit 1
+    fi
 
-if ! getent passwd postgres > /dev/null; then
-    chgrp postgres /etc/tpr/tern.conf
-fi
+    chown tpr:tpr /etc/tpr/tpr.conf
+
+    if ! getent passwd postgres > /dev/null; then
+        chgrp postgres /etc/tpr/tern.conf
+    fi
+}
+
+case "$1" in
+    configure)
+        ensure_users_and_permissions
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+exit 0
